services:
  - type: web
    name: ats-resume-matcher
    runtime: python

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      streamlit run app.py --server.port=$PORT --server.address=0.0.0.0